### ISSUE TITLE
Is node version limit necessary?

### ISSUE THREAD

**Issue by tearsofphoenix** [j-funk/fftw-js#1]
I noticed these lines in `package.json`
```json
"engines": {
    "node": "4.4.7^"
  },
```
When install the package using `yarn`, it'll throw an error, but `npm` will ignore this.
If node version is not that important, maybe just remove this configuration?

**Comment by j-funk** [comment]
@tearsofphoenix I updated the semantic versioning, I tested it with current version of `yarn` and and it works for me, let me know how it goes

**Comment by tearsofphoenix** [comment]
It goes well now. 😄
