### ISSUE TITLE
The npm package is not the same version as this repo.

### ISSUE THREAD

**Issue by zxol** [j-funk/fftw-js#17]
I tried to use this today and I got a version with a different api that was fftw.FFT and fftw.RFFT

Could you please republish the package with the correct API etc?

**Comment by j-funk** [comment]
Hi Andy, I'm sorry I don't have time to work on this.  If you post a PR I am happy to review / merge - or if you would like to become the maintainer / admin I am open to that as well.

**Comment by zxol** [comment]
Hi Julien.  Thank you for the offer, I'd like to help maintain this package. Let me know if this is OK with you, and if you need anything from me to facilitate the process. My npm username is the same as my github username, zxol.

**Comment by j-funk** [comment]
That's great, you should be all set Andy!  Thank you.

**Comment by zxol** [comment]
I appreciate it, thanks!
