### ISSUE TITLE
the precision of Float32Array is not enough

### ISSUE THREAD

**Issue by tearsofphoenix** [j-funk/fftw-js#3]
I'm working on using this library in a cryptography project. I found the precision of float can't 
is not enough, sometimes, it has even 0.0005 error compared to python version. So, why not
consider export Float64 version apis?
  I try to export function such as `fftw_plan_dft_r2c_1d`, but when run the scripts, node complain:
```
abort("Assertion failed: Cannot call unknown function fftw_plan_dft_r2c_1d (perhaps LLVM optimizations or closure removed it?)") at Error
```
Any help is appreciated!

**Comment by tearsofphoenix** [comment]
I have tried to modify the `Makefile.emscripten` : 
```Makefile
FFTW.js:
	emcc -O3 \
	     --memory-init-file 0 \
	     -s NO_FILESYSTEM=1 \
	     -s MODULARIZE=1 \
	     -s PRECISE_F32=1 \
	     -s EXPORT_NAME="'FFTWModule'" \
	     -s LINKABLE=1 \
	     -s EXPORT_ALL=1 \
	     -s ASSERTIONS=1 \
	     -o FFTW.js \
	     fftw-3.3.4/.libs/libfftw3f.a

clean:
	rm -f FFTW.js
```
It still show the former error. seems it can only export `fftwf_*` functions, right?

**Comment by j-funk** [comment]
If I were you, I would use a smaller, targeted export.  Choose the functions you want and export those.  The original file has: 

`-s EXPORTED_FUNCTIONS="['_fftwf_plan_r2r_1d','_fftwf_plan_dft_r2c_1d','_fftwf_plan_dft_c2r_1d','_fftwf_destroy_plan','_fftwf_execute']" \`

**Comment by j-funk** [comment]
RE: precision, I recently updated this repo to use `-s PRECISE_F32=1` which changes the default 64-bit floats to 32-bit.  If you use the earlier version `0.1.1` you should have higher precision.  Or you could recompile without `-s PRECISE_F32=1`.

**Comment by tearsofphoenix** [comment]
yeah, I know, first I tried 
```Makefile
-s EXPORTED_FUNCTIONS="['_fftw_plan_r2r_1d','_fftw_plan_dft_r2c_1d','_fftw_plan_dft_c2r_1d','_fftw_destroy_plan','_fftw_execute']" \
```
to export double-version-functions, but it not work. Then I tried to export all functions, still same error.
